# Generated by Django 4.1 on 2022-08-19 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_header', models.CharField(max_length=255)),
                ('notice_text', models.TextField()),
                ('notice_video', models.TextField(blank=True, null=True)),
                ('notice_time_create', models.DateTimeField(auto_now_add=True)),
                ('notice_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('notice_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.category', verbose_name='Категория объявления')),
                ('notice_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('answer_time_create', models.DateTimeField(auto_now_add=True)),
                ('answer_accepted', models.BooleanField(default=False, verbose_name='Комментарий принят')),
                ('answer_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='board.notice')),
                ('answer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('answer_post', 'answer_user')},
            },
        ),
    ]
