# Generated by Django 4.1 on 2022-08-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_accepted',
            new_name='answer_confirm',
        ),
    ]
